# Generated by Django 3.0.3 on 2020-03-30 17:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
